//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NYP.SvcRefFlyTA {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SvcRefFlyTA.IWsProgramCatalog")]
    public interface IWsProgramCatalog {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsProgramCatalog/GetPrograms", ReplyAction="http://tempuri.org/IWsProgramCatalog/GetProgramsResponse")]
        System.Data.DataSet GetPrograms();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsProgramCatalog/GetPrograms", ReplyAction="http://tempuri.org/IWsProgramCatalog/GetProgramsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetProgramsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWsProgramCatalogChannel : NYP.SvcRefFlyTA.IWsProgramCatalog, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsProgramCatalogClient : System.ServiceModel.ClientBase<NYP.SvcRefFlyTA.IWsProgramCatalog>, NYP.SvcRefFlyTA.IWsProgramCatalog {
        
        public WsProgramCatalogClient() {
        }
        
        public WsProgramCatalogClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsProgramCatalogClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsProgramCatalogClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsProgramCatalogClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetPrograms() {
            return base.Channel.GetPrograms();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetProgramsAsync() {
            return base.Channel.GetProgramsAsync();
        }
    }
}
